### PR TITLE
#805 File chooser for ModuleSelectionDialog

### LINKED ISSUE #805: Null reference to file object when exporting module
I'm seeing this error in the logs more often than I'd like to. So:
1. Figure out why it's happening - whether it's a bug in the code or some invalid IntelliJ state
2. If the former: fix it; if the latter: add a null check and display a notification of the error. If possible, attempt to fix the problem for the user.

Relevant stack trace:
```
java.lang.NullPointerException
	at fi.aalto.cs.apluscourses.intellij.actions.ExportModuleAction.actionPerformed(ExportModuleAction.java:108)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:240)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:240)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:248)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:236)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:67)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:240)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:90)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:90)
```

### PR DESCRIPTION
**Pull request by jaakkonarhi**
# Description of the PR

+ Fixes #805 

# Testing
<table>
  <tr>
    <th>unit</th>
    <th>integration</th>
    <th>e2e</th>
    <th>manual</th>
  </tr>
  <tr>
    <td>
      <ul>
        <li>- [ ] new <b>unit</b> tests created</li>
        <li>- [ ] all <b>unit</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [ ] new <b>integration</b> tests created</li>
        <li>- [ ] all <b>integration</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [ ] new <b>e2e</b> tests created</li>
        <li>- [ ] all <b>e2e</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [ ] <b>manual</b> testing went well</li>
      </ul>
    </td>
  </tr>
</table>  
  
# Have you updated the [TESTING.md](https://github.com/Aalto-LeTech/intellij-plugin/blob/master/TESTING.md) or other relevant documentation on _your_ branch?

- [ ] Yes.
- [ ] Not yet. I will do it next.
- [x] Not relevant.

### CODE REVIEW

File: src/main/java/fi/aalto/cs/apluscourses/presentation/ModuleSelectionViewModel.java [hunk 1]
```diff
@@ -3,6 +3,9 @@
 import static fi.aalto.cs.apluscourses.utils.PluginResourceBundle.getText;
 
 import com.intellij.openapi.module.Module;
+import com.intellij.openapi.project.Project;
+import com.intellij.openapi.project.ProjectUtil;
+import com.intellij.openapi.vfs.VirtualFile;
```
Comment (OlliKiljunen) [inline src/main/java/fi/aalto/cs/apluscourses/presentation/ModuleSelectionViewModel.java:8]: Ideally, we would like to keep the view model layer free of IntelliJ dependent stuff (but as it can be seen here, it wasn't that to begin with)

File: src/main/java/fi/aalto/cs/apluscourses/ui/exercise/ModuleSelectionDialog.java [hunk 2]
```diff
@@ -69,5 +76,16 @@ private void createUIComponents() {
...
+        (self, file) -> ((FieldPanel) fileChooser).setText(Optional.ofNullable(file).map(
+            VirtualFile::getPath).orElse("")));
+    ((FieldPanel) fileChooser).setEditable(false);
+  }
+
+  private void browse() {
+    var descriptor = FileChooserDescriptorFactory.createSingleLocalFileDescriptor();
+    FileChooser.chooseFile(descriptor, viewModel.getProject(), basePanel, viewModel.selectedModuleFile.get(),
+        viewModel.selectedModuleFile::set);
   }
```
Comment (OlliKiljunen) [inline src/main/java/fi/aalto/cs/apluscourses/ui/exercise/ModuleSelectionDialog.java:90]: Remark: Again ideally, this logic would be handled in a domain-independent subclass of FieldPanel that would have a a Bindable to be bound to the view model.

**Review by OlliKiljunen — APPROVED** [review]
Excellent work Very good (extremely quick) implementation. 👍

**Comment by OlliKiljunen** [comment]
An integration test fails because of a [server error](https://github.com/Aalto-LeTech/aplus-courses/runs/4336409286?check_suite_focus=true#step:7:816). It's possible that the problem was in the server side --> retry?

The rest of the failing tests is perhaps because the failing integration tests caused some classes not to be correctly loaded? 🤔

**Comment by jaakkonarhi** [comment]
I think they're failing because of BuildInfo, which was fixed later

**Review by Taikelenn — APPROVED** [review]
